__all__ = ("templates",)


# fastapi
from fastapi.templating import Jinja2Templates
from jinja2.environment import Environment
from jinja2.loaders import FileSystemLoader


# public instance of Jinja2Templates
templates = Jinja2Templates(
    env=Environment(  # basically the default environment generated by starlette
        loader=FileSystemLoader("templates"),
        autoescape=True,
        # enable_async=True,  # will raise "RuntimeError: this event loop is already running." when templates are used
    )
)
